Quote all the things

diff --git a/.bin/n b/.bin/n
--- a/.bin/n
+++ b/.bin/n
@@ -8,14 +8,14 @@ VERSION="1.0.0 (http://git.io/JlhrRQ)"
 N_PREFIX=${N_PREFIX-"$HOME/.bin/nodejs"}
 VERSIONS_DIR=$N_PREFIX/n/versions
 
-test -d $VERSIONS_DIR || mkdir -p $VERSIONS_DIR
+test -d "$VERSIONS_DIR" || mkdir -p "$VERSIONS_DIR"
 
 #
 # Logging.
 #
 
 log() {
-	printf "%10s: %s\n" $1 $2
+	printf "%10s: %s\n" "$1" "$2"
 }
 
 #
@@ -69,7 +69,7 @@ EOF
 #
 
 display_n_version() {
-	echo $VERSION && exit 0
+	echo "$VERSION" && exit 0
 }
 
 #
@@ -77,11 +77,11 @@ display_n_version() {
 #
 
 display_bin_path_for_version() {
-	test -z $1 && abort "version required"
+	test -z "$1" && abort "version required"
 	local version=${1#v}
 	local bin=$VERSIONS_DIR/$version/bin/node
-	if test -f $bin; then
-		printf $bin
+	if test -f "$bin"; then
+		printf "$bin"
 		echo
 	else
 		abort "v$1 is not installed."
@@ -120,7 +120,7 @@ display_remote_versions() {
 			# Active
 			printf "  \033[36m\u2713\033[0m $v\033[0m\n"
 		else
-			if test -d $VERSIONS_DIR/$v; then
+			if test -d "$VERSIONS_DIR/$v"; then
 				# Installed
 				printf "    $v \033[0m\n"
 			else
@@ -137,7 +137,7 @@ display_remote_versions() {
 #
 
 versions_paths() {
-	ls -d $VERSIONS_DIR/* 2> /dev/null \
+	ls -d "$VERSIONS_DIR/*" 2> /dev/null \
 	| egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
 	| sort -k 1,1n -k 2,2n -k 3,3n -t .
 }
@@ -168,8 +168,8 @@ display_versions_with_selected() {
 
 display_versions() {
 	check_current_version
-	test -z $active && abort "no versions installed"
-	display_versions_with_selected $active
+	test -z "$active" && abort "no versions installed"
+	display_versions_with_selected "$active"
 }
 
 #
@@ -177,9 +177,9 @@ display_versions() {
 #
 
 remove_versions() {
-	test -z $1 && abort "version(s) required"
+	test -z "$1" && abort "version(s) required"
 	while test $# -ne 0; do
-		rm -rf $VERSIONS_DIR/${1#v}
+		rm -rf "$VERSIONS_DIR/${1#v}"
 		shift
 	done
 }
@@ -189,7 +189,7 @@ remove_versions() {
 #
 
 is_ok() {
-	curl -Is $1 | head -n 1 | grep 200 &> /dev/null
+	curl -Is "$1" | head -n 1 | grep 200 &> /dev/null
 }
 
 #
@@ -201,8 +201,8 @@ activate() {
 	check_current_version
 	if test "$version" != "$active"; then
 		local dir=$VERSIONS_DIR/$version
-		if test -d $dir; then
-			rsync -K -a $dir/* $N_PREFIX
+		if test -d "$dir"; then
+			rsync -K -a "$dir/*" "$N_PREFIX"
 		fi
 	fi
 }
@@ -238,43 +238,43 @@ tarball_url() {
 install_node() {
 	local version=${1#v}
 
-	local dots=$(echo $version | sed 's/[^.]*//g')
+	local dots=$(echo "$version" | sed 's/[^.]*//g')
 	if test ${#dots} -eq 1; then
 		version=$($GET 2> /dev/null http://nodejs.org/dist/ \
 		| egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
 		| egrep -v '^0\.[0-7]\.' \
 		| egrep -v '^0\.8\.[0-5]$' \
 		| sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
-		| egrep ^$version \
+		| egrep "^$version" \
 		| tail -n1)
 
-		test $version || abort "invalid version v${1#v}"
+		test "$version" || abort "invalid version v${1#v}"
 	fi
 
 	local dir=$VERSIONS_DIR/$version
-	local url=$(tarball_url $version)
+	local url=$(tarball_url "$version")
 
-	if test -d $dir; then
-		activate $version
+	if test -d "$dir"; then
+		activate "$version"
 		exit
 	fi
 
 	echo
-	is_ok $url || abort "invalid version v$version"
-	log install $version
-	log mkdir $dir
-	mkdir -p $dir
+	is_ok "$url" || abort "invalid version v$version"
+	log install "$version"
+	log mkdir "$dir"
+	mkdir -p "$dir"
 	if [ $? -ne 0 ] ; then
 		abort "sudo required."
 	fi
 
-	cd $dir
+	cd "$dir"
 
-	log fetch $url
-	$GET $url | tar -zx --strip 1
+	log fetch "$url"
+	$GET "$url" | tar -zx --strip 1
 	printf "\033[1A\033[2K" # Erase line
-	activate $version
-	log installed $(node --version)
+	activate "$version"
+	log installed "$(node --version)"
 	echo
 }
 
@@ -314,9 +314,9 @@ else
 			ls|list) display_remote_versions; exit ;;
 			installed) display_versions ;;
 			-|rm|uninstall) shift; remove_versions $@; exit ;;
-			+|use|install) shift; install_node $1; exit ;;
-			latest) install_node $(get_latest_version); exit ;;
-			stable) install_node $(get_latest_stable_version); exit ;;
+			+|use|install) shift; install_node "$1"; exit ;;
+			latest) install_node "$(get_latest_version)"; exit ;;
+			stable) install_node "$(get_latest_stable_version)"; exit ;;
 			*) display_help ;;
 		esac
 		shift
